### ISSUE TITLE
ENH: Ping maintainer when issue starting to become stale

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-bot#101]
This request was specific to astropy core but might be beneficial to other repos too if we can generalize a way to list all the appropriate maintainers and/or escalation rules.

For example, an issue was opened about `astropy.stats` but it received no response for X amount of time (settable by bot controller), so bot posts a comment to ping the maintainer(s) responsible.

Stretch goal: Escalation -- If maintainer still does not respond, after Y amount of time, bot pings the CoCo.

Pull request -- This could possibly apply to PR too, although there is additional ambiguity whether the PR is stuck at pending author response or not.

**Comment by bsipocz** [comment]
I wonder how much it would be just spamming and making the issues more noisy knowing that not everyone is paying attention to their github notification feed even before this becomes a bot feature.

**Comment by pllim** [comment]
Well... We do have email addresses in the mail map... :japanese_ogre:

**Comment by bsipocz** [comment]
We don't want to burn all bridges 🔥 😉

**Comment by pllim** [comment]
Okay, if this suggestion is too radical, feel free to label it as "won't fix" and close it. :sweat_smile:

**Comment by bsipocz** [comment]
having the functionality and using it are two separate questions I guess.

**Comment by pllim** [comment]
I think @embray might be interested in this old discussion.

**Comment by embray** [comment]
@pllim Thanks, I'll work on this.

**Comment by embray** [comment]
To be clear, this would go hand-in-hand with my interest of automatically assigning maintainers of subpackages to issues (on an opt-in basis).

**Comment by bsipocz** [comment]
I'm still against assigning issues. PRs are different, but assigning issues are problematic for so many reasons.

**Comment by embray** [comment]
Why is it problematic, unless someone is against being assigned them?  My thinking was that it would be assigned as a "first level" of support.  The assignee would be free to re-assign it to someone else, unassign it, or do nothing at all (not much different from the status quo?).

**Comment by bsipocz** [comment]
If an issue is assigned it's much much less likely that a random person picks that up. While I don't see any guarantee that any maintainers, who didn't attend to the 80-100 issues they have for their subpackage and do regular triage would now suddenly actively work on them. So, in fact, auto assigning issue would dilute the info we already have now, e.g. now only cases that are actively wanted and needed to be solved get assigned.

**Comment by pllim** [comment]
I think I am going to close this as won't fix, but it is clear we have a consensus about PRs, so let's follow-up over at astropy/astropy#11051 . Thank you all for the enlightening discussions!
