### ISSUE TITLE
BUG: Bot stopped closing stale issues

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-bot#102]
As reported by @bsipocz , "I’m triaging [astropy core] and noticed that the 'close?' labelled issues are not being closed by the bot."

**Comment by pllim** [comment]
@astrofrog , do you think this is fixed by now?

**Comment by bsipocz** [comment]
No, it's not, e.g. this one has the label for 26 days ago, got the notification 19 days ago and is still open.
https://github.com/astropy/astropy/issues/8730
