### ISSUE TITLE
Add a new "check" for new "needs-copy-editing" label in main astropy repo

### ISSUE THREAD

**Issue by adrn** [astropy/astropy-bot#104]
We (@kelle @eteq @lglattly) have just added a new label to the main astropy repo: "needs-copy-editing". This label indicates that a given pull request touches the documentation *and* needs to be reviewed by @lglattly. The bot should check for the combination of "docs" and "needs-copy-editing" and fail a check if both are set on a pull request. This also means that, when applying the docs label to a pull request, we should also add the "needs-copy-editing" label. @lglattly will then remove the label after reviewing.

If possible, we should also have the bot request a review from @lglattly.

**Comment by kelle** [comment]
We've copyedited the copyedit label (F2F) and have figured out copyedit (verb) is one word. The label is "needs-copyediting".

**Comment by astrofrog** [comment]
For anyone interested in tackling this, this just involves writing a small plugin similar to https://github.com/astropy/astropy-bot/blob/master/astropy_bot/changelog_checker.py (but much much shorter)

**Comment by adrn** [comment]
Cool, thanks! I'll give it a try.

**Comment by pllim** [comment]
@adrn , API is at https://github.com/OpenAstronomy/baldrick . FYI. 🤖

**Comment by pllim** [comment]
While we are at this, maybe auto assign @adrn for review of PRs from @lglattly ?

p.s. I think this is a subset of #65 and maybe also a subset of a bigger question of enabling a feature like https://help.github.com/en/articles/about-code-owners
