### ISSUE TITLE
BUG: Autolabel not labeling three levels deep

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-bot#108]
`io.misc.ascii` did not get labelled in astropy/astropy#9100

**Comment by bsipocz** [comment]
It did label `io.misc.asdf` correctly on https://github.com/astropy/astropy/pull/9102 correctly, but then it shouldn't have added the `io.misc` label as well

**Comment by pllim** [comment]
Same for `visualization.wcsaxes` and `visualization` -- astropy/astropy#9153

**Comment by pllim** [comment]
We got the labeler on Action now, so closing this as won't fix.
