### ISSUE TITLE
ENH: [autolabel] Label "external" for things in "extern"

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-bot#114]
PRs like astropy/astropy#10021 that touch "extern" should have "external" label automatically applied.

**Comment by bsipocz** [comment]
Yes, and for the external case, it would very nice to also ping certain maintainers, as we want to make sure not to touch those besides bumping versions. (E.g. in many times people randomly wander into the external to fix pep8 or similar, when they should not touch those really).

**Comment by pllim** [comment]
> ping certain maintainers

Pinging maintainers might be too controversial.

**Comment by bsipocz** [comment]
ping  a subset of maintainers then, e.g. release manager. I certainly would like to see and stop any of those changes, from the POV of cutting the release (where we kind of say we ship x.y versions, so those versions should indeed be those versions not some randomly patched ones)
