### ISSUE TITLE
ENH: [autolabel] Run check every push?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-bot#115]
Should the autolabel check happen on every push instead of just once when PR is opened?

When I submitted a WIP PR, and then added more stuff to it later, the labels are misleading because packages I touched later are not automatically included.

Along the same line of thought, should label be removed when subsequent commits cause the PR to no longer touch a subpackage?

**Comment by bsipocz** [comment]
We talked about it, and decided against. E.g. consider the situation when a maintainer removed a label, but pushing a new commit would readd it? 
I'm not sure how much an issue that is though.

**Comment by pllim** [comment]
Yeah, okay, now I remember. Let's close then. Thanks!
