### ISSUE TITLE
Failure to find previous comment when there are too many comments

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-bot#13]
See https://github.com/astropy/astropy/pull/6176#issuecomment-315643875

**Comment by bsipocz** [comment]
Isn't the issue there that it's an old PR? I suspect this issue will only affect those already opened PRs, as normally the bot will be the first one to comment, so even if the existing comments are checked in chunks the bot's will be in the first batch always?

**Comment by astrofrog** [comment]
Right, though it'd be nice to make sure that it works for old PRs, since there are still a bunch open (to avoid issues like this)

**Comment by bsipocz** [comment]
I've quickly tried to run it locally to fix this, but it doesn't seem to be as trivial as expected so I give up.

**Comment by pllim** [comment]
Will caching be a feasible solution? Like, keep a record of where the bot had left a comment before and look it up before attempting to post a new comment?

**Comment by astrofrog** [comment]
@pllim - no, we can't assume any persistent data on the server (one has to pay for persistent data, and things are a lot cleaner if we don't rely on databases)

**Comment by astrofrog** [comment]
I think this should be fixed, but let me know if not!
