### ISSUE TITLE
Make astrochangebot configurable

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-bot#2]
Some projects may want to be less strict about changelogs or milestones, e.g. doesn't require the changed to be added by the contributor but leaves it as a pre-release maintaner task.

**Comment by astrofrog** [comment]
One thing that needs to be settable is the name of the changelog. At the moment we just try different filenames.

**Comment by bsipocz** [comment]
yes, that one, too

**Comment by astrofrog** [comment]
By the way, maintainers can add the changelog entry themselves pre-merge if contributors can't do it, which would be cleaner since it keeps the changelog entry defined in the PR it relates to (and avoids issues when backporting where the changelog commit might be forgotten).

**Comment by bsipocz** [comment]
Yes, that's right. But in astroquery, so far, I found it easier to do it in one go and have just one summary entry for many bugfixes. But then there is no bugfix branching here.

**Comment by astrofrog** [comment]
@bsipocz - agree, though if you do that you lose the benefit of using a bot like this and you'll have to run the consistency checking manually later (and may run into issues). It's completely up to the maintainers though, I think for the core package I'd like to see people always try and get the bot status to pass.

**Comment by bsipocz** [comment]
yes, totally agree it's the way to go with the core and also the helpers.

**Comment by astrofrog** [comment]
Coming back to this again, I agree we need a way to enable/disable the changelog checking on a per-repo basis. At the moment the auto-closing can only be used if the app is added to a repo, which enables the changelog checking in PRs.

**Comment by bsipocz** [comment]
Oh, and then it would be nice to configure the time frames for the auto-closure, too.

**Comment by pllim** [comment]
You can now expand upon the YAML stuff now that #42 is merged.

**Comment by astrofrog** [comment]
I think this is now fixed - with baldrick, each repo can provide its own ``pyproject.toml`` to override the general ``astropy-bot`` settings.
