### ISSUE TITLE
Test GitHub API classes

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-bot#33]
There are two ways we can do this - either we set up a test repo and then actually interact with that repo, or we mock the GitHub server and return pre-determined JSON responses. I think the latter is safer in terms of continuous integration.

**Comment by pllim** [comment]
👍 on mock. But we should keep the test repo up for human testing.

**Comment by pllim** [comment]
I added a bunch of tests. Coverage > 80% now. Maybe okay to close this?

**Comment by astrofrog** [comment]
Closing this - thanks @pllim! (and the code is now in baldrick)
