### ISSUE TITLE
Make bot recomment for premature merges

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-bot#4]
If a PR is merged without all comments of the bot being addressed, it should comment again after the merge as it's quite probable that the original comment was overseen in a longish thread of discussions for a PR.

**Comment by astrofrog** [comment]
Good idea - note that even if the comment gets lost in all the discussion, the CI status should still make it clear things are failing (and as mentioned in #3 we can make the Details link link to the comment)

**Comment by bsipocz** [comment]
Oh, sure I forgot about that. Also any discrepancies could be picked up later when running the release checking scripts.
