### ISSUE TITLE
Only notify for staleness, but don't close

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-bot#46]
@olebole pointed out on ``astropy-dev`` that there are a few cases where the PR is not merged due to the unfinished review process. This may be especially true for the low traffic, high maintained burdened repos like ``astropy-helpers`` or ``package-template``.

It may be useful to have a configurable option of not only having custom times for first notification and closure time, but also to only have a notification of possible staleness. 

We may also want to make the message of the bot configurable, to point out what the author could do to make sure the PR doesn't get closed if it's not merged due to lack of review or someone pushing the merge button.

**Comment by astrofrog** [comment]
Isn't that what the **keep-open** label does? (prevent this kind of situation I mean)

**Comment by bsipocz** [comment]
Well, Ole had a good point about the in certain places (helpers?) PR could slip through under the radar to be waiting for the same maintainer to add the ``keep-open`` label as doing the review. 

For core, I feel that we're good with the current setup as at least there are @pllim and me doing generic triaging and can ping submodule maintainers or add the label if needed.

**Comment by astrofrog** [comment]
This could be done in https://github.com/astropy/astropy-bot/pull/42 potentially?

**Comment by bsipocz** [comment]
I wouldn't want to hold up merging #42 because of it, but if @pllim has the time soonish, then sure.

**Comment by pllim** [comment]
Adding in #42 shouldn't be a problem but I am waiting for a review there on how to proceed.

**Comment by pllim** [comment]
Part of this is now possible with #42 merged. Message customization still needs work.
