### ISSUE TITLE
Delay first comment of the bot for non-maintainer PRs

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-bot#5]
Maintainers can set all the bot required thing, but others can't, so it would be nice to give a maintainers a chance to get to the PR first and set labels and milestones.

**Comment by astrofrog** [comment]
This is harder than it might seem, because we don't want to just e.g time.sleep since that would hold up the server which wouldn't be able to accept any other requests. Maybe we can start a thread with some delay.

**Comment by astrofrog** [comment]
Has this really been an issue though? Can we close this @bsipocz?

**Comment by bsipocz** [comment]
This is still something that's a would be nice think, but probably doesn't worth the effort of implementing it. No one complained I believe, or they kept it very close to themselves.
