### ISSUE TITLE
Add closed-by-bot label when auto-closing

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-bot#54]
If the closed-by-bot label exists in the repository, it should be added when the bot auto-closes issues/PRs so these can be easily found in future. For now I've labelled PRs and issues manually.

**Comment by pllim** [comment]
> If the closed-by-bot label exists

Should the bot be given power to *create* this label if it does not exist? Or is that too skynet-y?

**Comment by astrofrog** [comment]
I would say it shouldn't create the label for now

**Comment by bsipocz** [comment]
Well, the label only needs to be created the first time, so very well a human can do it a double check when setting up the bot...

**Comment by pllim** [comment]
Isn't this already implemented?

**Comment by astrofrog** [comment]
No, the existing labels were put manually :)

**Comment by pllim** [comment]
:scream:
