### ISSUE TITLE
Provide default values for environment vars

### ISSUE THREAD

**Issue by Cadair** [astropy/astropy-bot#58]
I was just spinning up my own version of this, and it's a pain to have to set a whole bunch of stale env vars which I am not using 😆

**Comment by pllim** [comment]
Related to #2? Also if you have a list of those pesky undefined var names, please list them out.

**Comment by Cadair** [comment]
semi-related to #2. The list is here: https://github.com/astropy/astropy-bot/blob/master/changebot/webapp.py#L18

obviously the required tokens are requried, would be good to check if the stale checker was enabled before the others were required though.

**Comment by pllim** [comment]
This would involve quite a bit of clean up and refactoring. Maybe a sprint at pyastro... :wink:

**Comment by bsipocz** [comment]
sprinting on the bot is already on my ever growing list for pyastro 😉

**Comment by astrofrog** [comment]
Closing this as I think now only a strict minimum of env vars are required (and by baldrick, not here)
