### ISSUE TITLE
ENH: bot to detect lack of test and insert this meme

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-bot#61]
When PR is submitted, if bot does not find any changes to any Python file  under some `tests` directory, insert this (thanks to @drdavella via astropy/astropy#7359):

![darth_vader_no_tests](https://user-images.githubusercontent.com/2090236/38684020-c280289e-3e3c-11e8-939d-a084c47df503.png)

Optional: When maintainer label the PR as "doc" (or perhaps other labels that imply no tests are necessary), bot goes back to that comment and remove the meme.

**Comment by astrofrog** [comment]
👍 - PR welcome!

**Comment by astrofrog** [comment]
Although maybe we can NOT do it for first-time contributors (GitHub shows if users are first-time contributors, so hopefully it's also in the API)

**Comment by pllim** [comment]
First timer status is at https://developer.github.com/v4/reference/enum/commentauthorassociation/ . But that seems different from https://developer.github.com/v3/ :woman_shrugging:
