### ISSUE TITLE
Use GitHub API v4 (GraphQL)?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-bot#62]
xref spacetelescope/repostats#26

**Comment by pllim** [comment]
@crawfordsm said he might be able to provide some ideas on this.

**Comment by stscicrawford** [comment]
Yes RESTful to GraphQL is a pretty major change, and we were starting from scratch so we weren't migrating a python library.  Currently, for Github interactions, I've been using https://github.com/PyGithub/PyGithub but that is still v3.  Is there a date for the depreciation of the v3?

**Comment by pllim** [comment]
I haven't seen any news about deprecating v3, so there is no urgency on switching. But on the other hand, switching sooner means there is less to port later. So... :woman_shrugging: 

The bot does not use PyGithub, which by the way has GPL license (!).

**Comment by pllim** [comment]
Do you have any Python library to recommend in terms of interfacing with v4 GraphQL? Thanks!

**Comment by pllim** [comment]
GraphQL support seems to be immature still right now. Let's hold off on this. Here's a reply from GitHub:
<hr/>
If you have any other feature requests for the GraphQL API, we recommend creating a new Topic for this in our GitHub Platform Forum's GraphQL API section and tagging it as a schema-request so the team can take a look. Our team wrote more about this process here:

https://platform.github.community/t/add-your-schema-requests/25/83

Also, I recommend checking out our available Libraries for interfacing with the GitHub API:

https://developer.github.com/v3/libraries/

Octokit is officially supported by GitHub, but there are third-party libraries (including Python!) that you may be interested in using for your project.

**Comment by pllim** [comment]
2 years on, v4 still pretty useless.
