### ISSUE TITLE
bot should not complain on post-release change log update

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-bot#64]
Bot was complaining unnecessarily in astropy/astropy#7403, whose purpose is to update the change log post-release.

*"Changelog entry present but no-changelog-entry-needed label set"*

When a PR *only* changes the change log, bot should skip check?

**Comment by bsipocz** [comment]
Yes, I think that would be a sensible option. If we want extra insurance, it could check whether the PR owner is a maintainer or not, but with a quick check it wasn't obvious whether that can be done easily.

**Comment by pllim** [comment]
Getting maintainer list might need special privilege. Is this the correct API to use -- https://developer.github.com/v3/repos/#list-teams ? If so, https://api.github.com/repos/astropy/astropy/teams didn't return anything useful.

**Comment by bsipocz** [comment]
hmm, weird, maybe only org admins have access to it even though the web interface allows listing teams.

Anyway, I think it's safe to just hard wire a few usernames who are likely to ever open such cleanup PRs for maintenance purposes...

**Comment by astrofrog** [comment]
What about just adding a label 'skip-changelog-checks'?

**Comment by astrofrog** [comment]
Also maybe this doesn't really matter since maintainers can merge PRs even if the checks fail (I'd rather not hard-code usernames in the bot code)

**Comment by bsipocz** [comment]
yeah, the issue is really just the eyesore of the red x for the PR, I'm happy with any solutions for that.

**Comment by pllim** [comment]
Tagging as suggested in https://github.com/astropy/astropy-bot/issues/64#issuecomment-395392734 sounds easy and reasonable. :+1:

**Comment by pllim** [comment]
Update: I added the suggested label over at Astropy core and submitted #85 to go with it.
