### ISSUE TITLE
Feature Request: Bring back HAL profile pic 

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-bot#7]
Never found it hostile, or is it just me? 😄

**Comment by eteq** [comment]
I am pro-HAL!

**Comment by eteq** [comment]
Or maybe a 50/50 alpha of the two?

**Comment by eteq** [comment]
Something like:
![image](https://user-images.githubusercontent.com/346587/27883993-a32cc0b6-61a0-11e7-834e-5cef80cb9136.png)

**Comment by pllim** [comment]
Whoa @eteq , that's quite hypnotic! :cyclone: :eye: :cyclone:

**Comment by astrofrog** [comment]
I like HAL too, but I think we should keep that in case we still need @astrobot (not @astropy-bot). You know, in case we need a kind of good bot / bad bot thing.

**Comment by bsipocz** [comment]
though we should change @astrobot from HAL to the one @eteq suggested above.

**Comment by pllim** [comment]
But how about SAL for `astropy-bot` then? (Looks like HAL but in blue.) http://2001.wikia.com/wiki/SAL_9000
