### ISSUE TITLE
MNT: Delete stale branches?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-bot#72]
@astrofrog , I see there are 3 other branches here besides `master` (`cron`, `fix-comments`, `ny-sprint`). I propose we delete them if they are stale. This is because when people fork the repo, they unnecessarily inherit those branches as well. Just my OCD speaking. What do you think?

**Comment by bsipocz** [comment]
👍 to this from me.

**Comment by pllim** [comment]
I am just unsure about `cron` branch. @astrofrog , are you using any of those for your own world domination?

**Comment by astrofrog** [comment]
``cron`` is what we use to run the checks of stale issues/prs! The other two branches can be deleted.

**Comment by astrofrog** [comment]
Done, closing! (I've also protected ``master`` and ``cron``)

**Comment by pllim** [comment]
@astrofrog , but `cron` is also over 200 commits behind `master`! Does this mean that stale issues/PRs checker is not picking up the bot improvements that we put in recently? :scream:
