### ISSUE TITLE
TST: CircleCI failing on master branch

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-bot#79]
Looks like I might have accidentally broke it on May 4. I didn't even know we have CircleCI set up for the bot. I only just now noticed it when I saw red "x" in the commit history web UI.

https://circleci.com/gh/astropy/astropy-bot/1?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by pllim** [comment]
Looks like it is missing some necessary dependencies. Who set this up? Please help...

**Comment by astrofrog** [comment]
I just set up CircleCI today - there isn't any config on master yet! So just ignore the failure :)

**Comment by astrofrog** [comment]
It's for the PR stuart added, which does have a CircleCI config file
