### ISSUE TITLE
Allow affects-dev w/changelog entry

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-bot#8]
Sometimes affects-dev *and* changelog entry can be true, for example if editing an old changelog entry - astropy/astropy#6334

**Comment by bsipocz** [comment]
I think this case we just shouldn't use the ``Affects-dev`` label?

**Comment by astrofrog** [comment]
Well affects-dev could be an indication it's *ok* to not have a changelog entry (synonymous with no-changelog-entry-needed), but it shouldn't complain if there is an entry anyway.

**Comment by bsipocz** [comment]
Oh, OK. Either way is fine by me :)
