### ISSUE TITLE
Bot worries about no-changelog-entry-needed when milestone is not set

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy-bot#80]
See https://github.com/astropy/astropy/pull/7489
It claims that "Changelog entry present but no-changelog-entry-needed label set", when really the only problem is that the milestone is not set.

**Comment by bsipocz** [comment]
@mhvk - You have the `no-changelog-entry-needed` label and also a changelog entry. 

So I'm afraid, but the bot seems to be right this time, please remove the label 😃

**Comment by mhvk** [comment]
Oops, that's what I get for building on top of another PR!!!
