### ISSUE TITLE
Move in-repo configuration to pyproject.toml

### ISSUE THREAD

**Issue by Cadair** [astropy/astropy-bot#83]
It seems that various projects are adopting the `pyproject.toml` file as described by [PEP 518](https://www.python.org/dev/peps/pep-0518/) for configuration of tools that operate on the repo. (Examples I have found are [towncrier](https://github.com/hawkowl/towncrier) [tidypy](https://github.com/jayclassless/tidypy) and [poetry](https://github.com/sdispater/poetry)).

Given that I have now written a changelog processor for towncrier and am therefore reading this toml file anyway, how would you feel about moving the `.astropybot.yml` config into a `tool.botname` section in `pyproject.toml`?

**Comment by Cadair** [comment]
I have code for this now btw and I am using it for sunpybot to prevent the addition of yet another file in the root of the repo, so if you want it it's yours.

**Comment by pllim** [comment]
Since it is an accepted PEP, I don't have any objection. @astrofrog and @bsipocz ?

@Cadair , feel free to open another PR with your suggestion on how it should be used. :smile:

**Comment by bsipocz** [comment]
I'm not convinced by the examples that it's widely used yet, but given it's an accepted PEP and the motivation makes sense, so why not be amongst the first ones to use it. 
PR is welcome :)

**Comment by Cadair** [comment]
Yeah it dosen't seem to be that widely used, but I like the concept of having one config file to put all the stuff in rather than each thing having its own.

I will rebase my branches and send a PR.

**Comment by Cadair** [comment]
#84

**Comment by pllim** [comment]
Implemented in #84.
