### ISSUE TITLE
ENH: Auto open issue on Astropy when new CFITSIO is released

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-bot#86]
Idea: Have the bot check https://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/docs/changes.txt every so often and detect new CFITSIO release. If positive, open a new issue on Astropy core repo.

Idea originated from discussions related to spacetelescope/hstcal#316

**Comment by bsipocz** [comment]
👍 

I wonder, do we have similarly critical bundles? I mean it's not an issue not to update any of the js stuff or ply, but probably the same machinery can be used to notify for updates of erfa and wcslib, too.

**Comment by pllim** [comment]
@bsipocz , as long as the release is announced somewhere that is consistently parsable, I don't see why not.

**Comment by bsipocz** [comment]
Yeah, that's tough. Can we rely on the copyright note at the top of the webpage/a choosen file? (http://www.atnf.csiro.au/people/mcalabre/WCS/wcslib/). Erfa is even less easy given we should really poll SOFA and notify ERFA to do the updates, then do update the bundled one in astropy.

We can poll the big red date for SOFA on their main page (http://www.iausofa.org/ or in the title of http://www.iausofa.org/current.html), but then again, I'm not sure how future proof that is.

**Comment by pllim** [comment]
Hmm this is sounding like `astroreleasechecker` (like `astroquery` but for releases)...?

**Comment by bsipocz** [comment]
or even a `releasechecker`, as e.g. `expat` is not astro

**Comment by pllim** [comment]
This might be already possible with https://github.com/spacetelescope/harbinger written by @rendinam
