### ISSUE TITLE
Would it be possible to fix these?  No, I am not a maintainer.

### ISSUE THREAD

**Issue by cclauss** [astropy/astropy-bot#92]
@astropy-bot says:
> * The milestone has not been set (this can only be set by a maintainer)
> * Changelog entry not present (or pull request number missing) and neither the Affects-dev nor the no-changelog-entry-needed label are set
>
> Would it be possible to fix these? Thanks!

Couldn't the bot first look to see I am a __maintainer__ and then determine that because I am _not_ a maintainer that I can neither set the milestone nor set labels?

**Comment by bsipocz** [comment]
@cclauss - Thanks for the feedback. Sadly it's not possible for the bot to check who is a maintainer. However the bot is currently undergoing a refactoring that may eliminate adding a comment altogether.

However that comment is going to be updated when a milestone is set, changelog added, etc.

**Comment by astrofrog** [comment]
I'm going to close this as we now no longer post the comment and use status checks instead.
