### ISSUE TITLE
Astrobot seems to repeat its messages

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy-bot#95]
I got three at https://github.com/astropy/astropy/pull/8128

**Comment by pllim** [comment]
Yes, it is a known issue and probably some bug upstream on GitHub. @astrofrog tried adding a `time.sleep` but it didn't work.

**Comment by astrofrog** [comment]
It's more of a race condition than a bug - we just handle all the events from GitHub faster than GitHub can post the comment.

**Comment by mhvk** [comment]
Yes, github seems to have become much slower than it used to. I hope it is not meant just to get people to sign up for paid service.

**Comment by astrofrog** [comment]
This should now be fixed since I've changed astropy-bot to post individual status checks rather than a comment, so this shouldn't happen anymore in astropy-bot (but opening https://github.com/OpenAstronomy/baldrick/issues/40 as a general baldrick issue)

**Comment by pllim** [comment]
@astrofrog , does the README need to be updated to document how to install the bot as "status check"? Or is this all being done under the hood over at Baldrick?

**Comment by astrofrog** [comment]
@pllim - that should be described in https://baldrick.readthedocs.io/en/latest/plugins.html - but feel free to open a PR for the README here if you think we can make things like that clearer.
